#!/bin/sh

ADVCPMV_VERSION=${1:-0.9}
CORE_UTILS_VERSION=${2:-9.5}
coreutils_version=$CORE_UTILS_VERSION

DOCKER_IMG=alpine:latest
TARGET_DIR="coreutils"
#TARGET='`find src -type f -executable`'
TARGET='bin/*'
PKG_CMD="apk add --no-cache git tar curl xz upx build-base perl acl-dev libcap-dev acl-static libcap-static"
DOWNLOAD_CMD="
	curl -o - http://ftp.gnu.org/gnu/coreutils/coreutils-${coreutils_version}.tar.xz | tar xJ \
	&& mv coreutils-${coreutils_version} coreutils
"
BUILD_CMD="
	curl -LO https://raw.githubusercontent.com/jarun/advcpmv/master/advcpmv-$ADVCPMV_VERSION-$CORE_UTILS_VERSION.patch \
	&& { patch -N -p1 -i advcpmv-$ADVCPMV_VERSION-$CORE_UTILS_VERSION.patch || true; } \
	&& env FORCE_UNSAFE_CONFIGURE=1 CFLAGS='-Os -ffunction-sections -fdata-sections' LDFLAGS='-Wl,--gc-sections -static' ./configure && make -j$(nproc) \
	&& mv src/cp src/advcp && mv src/mv src/advmv \
	&& { mkdir bin || true; } && mv \$(find src -type f -executable) bin \
	&& strip -s -R .comment -R .gnu.version --strip-unneeded $TARGET || true \
	&& upx --lzma --ultra-brute $TARGET || true
"

CLEANUP_CMD="make clean"
