#!/bin/sh

DOCKER_IMG=alpine:latest
TARGET_DIR="dwm"
TARGET=dwm
PKG_CMD="apk add --no-cache git upx tar build-base libx11-dev libxft-dev libxinerama-dev"
DOWNLOAD_CMD="git clone --depth=1 https://git.suckless.org/dwm \"$TARGET_DIR\""
BUILD_CMD="sed -i 's#define MODKEY Mod1Mask#define MODKEY Mod4Mask#' config.def.h \
	&& make -j$(nproc) && rm config.h
"
CLEANUP_CMD="make clean"
