#!/bin/sh

DOCKER_IMG=alpine:latest
TARGET_DIR="hexcurse"
TARGET=hexcurse
PKG_CMD="apk add --no-cache git upx tar build-base automake autoconf ncurses-dev ncurses-static"
DOWNLOAD_CMD="git clone --depth=1 https://github.com/LonnyGomes/hexcurse \"$TARGET_DIR\""
BUILD_CMD="sed -i 's#^FILE \*fpIN;#extern FILE *fpIN;#' include/hex.h \
	&& grep 'FILE \*fpIN;' src/hexcurse.c >/dev/null || sed -i '\$a FILE *fpIN;' src/hexcurse.c \
	&& rm -rf ./configure~ autom4te.cache aclocal.m4 \
	&& LDFLAGS=-static ./configure \
	&& ln -sf \$(which aclocal) \$(which aclocal)-1.15 \
	&& ln -sf \$(which automake) \$(which automake)-1.15 \
	&& make -j$(nproc) \
	&& mv src/$TARGET ."
CLEANUP_CMD="make clean"
