#!/bin/sh

DOCKER_IMG=alpine:latest
TARGET_DIR="iproute2"
TARGET='bin/*'
PKG_CMD="apk add --no-cache git upx build-base flex bison linux-headers"
DOWNLOAD_CMD="git clone --depth=1 https://git.kernel.org/pub/scm/network/iproute2/iproute2 \"$TARGET_DIR\""
BUILD_CMD="LDFLAGS=-static make -j$(nproc) && { mkdir bin || true; } && find ./ip -type f -executable -exec mv {} bin/ +"
CLEANUP_CMD="make clean"
