#!/bin/sh

DOCKER_IMG=alpine:latest
TARGET_DIR="pigpio"
TARGET=
PKG_CMD="apk add --no-cache git upx build-base"
DOWNLOAD_CMD="git clone --depth=1 https://github.com/joan2937/pigpio \"$TARGET_DIR\""
BUILD_CMD="make -j$(nproc) CFLAGS='-std=gnu11'"
#CLEANUP_CMD="make clean"
