#!/bin/sh

DOCKER_IMG=alpine:latest
TARGET_DIR="unzip60"
TARGET="funzip unzip unzipsfx"
PKG_CMD="apk add --no-cache curl tar upx build-base"
DOWNLOAD_CMD="curl -L https://sourceforge.net/projects/infozip/files/UnZip%206.x%20%28latest%29/UnZip%206.0/unzip60.tar.gz/download | tar xz"
BUILD_CMD="{ git clone --depth 1 https://gitlab.alpinelinux.org/alpine/aports || true; } && for p in aports/main/unzip/*.patch; do patch -N -p1 < \"\$p\" || true; done && make -f unix/Makefile unzips -j$(nproc) LF2=-static CF='-I. -DACORN_FTYPE_NFS -DWILD_STOP_AT_DIR -DLARGE_FILE_SUPPORT -DUNICODE_SUPPORT -DUNICODE_WCHAR -DUTF8_MAYBE_NATIVE -DNO_LCHMOD -DDATE_FORMAT=DF_YMD -DNOMEMCPY -DNO_WORKING_ISPRINT'"
CLEANUP_CMD="make -f unix/Makefile clean"
