#!/bin/sh

DOCKER_IMG=alpine:latest
TARGET_DIR="zip30"
TARGET="zip zipsplit zipnote zipcloak"
PKG_CMD="apk add --no-cache curl tar upx build-base"
DOWNLOAD_CMD="curl -L https://sourceforge.net/projects/infozip/files/Zip%203.x%20%28latest%29/3.0/zip30.tar.gz/download | tar xz"
BUILD_CMD="{ git clone --depth 1 https://gitlab.alpinelinux.org/alpine/aports || true; } && for p in aports/main/zip/*.patch; do patch -N -p1 < \"\$p\" || true; done && LDFLAGS=-static make -f unix/Makefile generic -j$(nproc)"
CLEANUP_CMD="make -f unix/Makefile clean"
