#!/bin/sh

DOCKER_IMG=alpine:latest
TARGET_DIR="zip30"
TARGET="zip zipsplit zipnote zipcloak"
PKG_CMD="apk add --no-cache curl tar upx build-base"
DOWNLOAD_CMD="curl -L https://sourceforge.net/projects/infozip/files/Zip%203.x%20%28latest%29/3.0/zip30.tar.gz/download | tar xz"
BUILD_CMD="make -f unix/Makefile os390 -j$(nproc) LFLAGS1='-static'"
CLEANUP_CMD="make -f unix/Makefile clean"
